---
- name: "update apt packages."
  become: yes
  apt:
    update_cache: yes

- name: "upgrade packages"
  become: yes
  apt:
    upgrade: yes

- name: "install dependencies"
  become: yes
  apt:
    name: ["python", "nodejs", "npm"]
    state: latest
    update_cache: yes

- name: "install pm2"
  command: sudo npm install pm2
