---
- name: Make web directory
  file:
    path: /home/ubuntu/web/
    state: directory

- name: "Extract Dist"
  unarchive:
    src: "{{ artifact_filename }}"
    dest: /home/ubuntu/web/

- name: "Set environment variables"
  template:
    src: env.j2
    dest: /home/ubuntu/web/.env

- name: "Install"
  command: npm install
  args:
    chdir: /home/ubuntu/web

- name: "Start pm2"
  command: pm2 start npm -- start
  args:
    chdir: /home/ubuntu/web

- name: "Install node_exporter"
  become: yes
  command: "{{ item }}"
  with_items:
    - id -u node_exporter &>/dev/null || useradd node_exporter
    - wget https://github.com/prometheus/node_exporter/releases/download/v1.0.1/node_exporter-1.0.1.linux-amd64.tar.gz
    - tar xzf node_exporter-1.0.1.linux-amd64.tar.gz
    - sudo cp node_exporter-1.0.1.linux-amd64/node_exporter /usr/local/bin/node_exporter
    - rm -rf node_exporter-1.0.1.linux-amd64.tar.gz node_exporter-1.0.1.linux-amd64

- name: "Configure node_exporter"
  become: yes
  template:
    src: node_exporter.j2
    dest: /etc/systemd/system/node-exporter.service

- name: "Configure systemd"
  become: yes
  command: "{{ item }}"
  with_items:
    - sudo systemctl daemon-reload
    - sudo systemctl enable node-exporter
    - sudo systemctl start node-exporter
    - sudo systemctl status node-exporter
