---
- name: Make web directory
  file:
    path: /home/ubuntu/web/
    state: directory

- name: "Extract Dist"
  unarchive:
    src: "{{ artifact_filename }}"
    dest: /home/ubuntu/web/

- name: "install"
  command: npm install
  args:
    chdir: /home/ubuntu/web

# - name: "stop pm2"
#   command: pm2 stop default
#   args:
#     chdir: /home/ubuntu/web

- name: "start pm2"
  command: pm2 start npm -- start
  args:
    chdir: /home/ubuntu/web
