---
- name: Make web directory
  file:
    path: ~/web
    state: directory

- name: "Extract Dist"
  unarchive:
    src: "{{ artifact_filename }}"
    dest: ~/web/

- name: "install pm2"
  become: yes
  command: npm install
  args:
    chdir: ~/web

- name: "stop pm2"
  command: pm2 stop default
  args:
    chdir: ~/web

- name: "start pm2"
  command: pm2 start npm -- start
  args:
    chdir: ~/web
