---
- name: Make web directory
  file:
    path: ~/web
    state: directory

- name: "Extract Dist"
  unarchive:
    src: "{{ artifact_filename }}"
    dest: ~/web/

- name: "install dist"
  command: npm install
  args:
    chdir: /home/ubuntu/web/dist

- name: "stop pm2"
  command: pm2 stop default
  args:
    chdir: /home/ubuntu/web/dist

- name: "start pm2"
  command: pm2 start npm -- start
  args:
    chdir: /home/ubuntu/web/dist
